name: Build Docker Image

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set version tag
        id: set-version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Login to Docker Hub
        id: docker-hub
        env:
          DOCKER_USERNAME: dubemezeagwu
          DOCKER_PASSWORD: docker@123
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - name: Build the Docker image
        id: build-docker-image
        run: |
          ls -la
          docker build -f ./server/Dockerfile -t dubemezeagwu/ece9065-test:${{ env.version }} .
      - name: Push the Docker image
        id: push-docker-image
        run: docker push dubemezeagwu/ece9065-test:${{ env.version }}
